api = "0.2"

[buildpack]
id = "la-haus/ruby-test"
version = "0.1.4"
name = "Ruby"
ruby_version = "3.1.2"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack"
